In [2]:
import numpy as np

In [47]:
#np.matrix([],[]) toma todas las propiedades de una matriz, es más facil hacer la multiplicación y las operaciones con matrices
A=np.matrix([[4,-8],[5,10]])
B=np.matrix([[3,2],[-7,6]])
C=np.zeros([2,2])
for i in range(len(A)):
    for j in range(len(A[i])):
        C[i]=A[i][j]+B[i][j]
print(A)
        
D=np.zeros([2,2])
for i in range(len(A)):
    for j in range(len(A[i])):
        D[i]=B[i][j]+A[i][j]
print(D)

C=np.zeros([2,2])
for i in range(len(A)):
    for j in range(len(A[i])):
        C[i]=A[i][j]-B[i][j]
print(C)        

np.linalg.det(C)


[[ 4 -8]
 [ 5 10]]
[[ 7. -6.]
 [-2. 16.]]
[[  1. -10.]
 [ 12.   4.]]


124.00000000000003

In [54]:
mult=np.zeros([2,2])   #tarea
for i in range(len(A)):
    col=0
    for j in range(len(B)):
        col=A[0][0]*
        
        

ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

In [66]:
a=np.array([[2,3,-1],[-1,9,2],[4,12,3]])
b=np.array([10,5,19])
c=np.linalg.eig(a)

In [68]:
c

(array([ 1.13282201+2.47605348j,  1.13282201-2.47605348j,
        11.73435598+0.j        ]),
 array([[ 0.17981881+0.49919102j,  0.17981881-0.49919102j,
          0.09033634+0.j        ],
        [-0.18852389+0.00411784j, -0.18852389-0.00411784j,
          0.56621863+0.j        ],
        [ 0.8263869 +0.j        ,  0.8263869 -0.j        ,
          0.81928982+0.j        ]]))