In [6]:
import numpy as np
import random


In [53]:
#Ejercicio 1 (Sin Numpy)
#Matriz de 15x15 con valores enteros aleatorios
filas=15
columnas=15
x=[]
for i in range(filas):
    x.append([])
    for j in range(columnas):
        x[i].append(random.randint(1,50))
print(x)
#Diagonal secundaria igualada a cero
for i in range(filas):
    if i==0:
        x[i][-1]=0
    else:
        x[i][-i-1]=0
print(x)
#Multiplos de 3 por fila
for i in range(filas):
    cont=0
    for j in range(len(x[i])):
        if x[i][j]%3==0:
            cont+=1
    print("En la fila ",i," hay", cont, "multiplos de 3")
        
#Numeros pares e impares
par=0
impar=0
for i in range(filas):
    for j in range(len(x[i])):
        if x[i][j]%2==0:
            par+=1
        elif x[i][j]%2!=0:
            impar+=1
print(f"En la matriz hay {par} números pares y {impar} números impares")
#Cada 5 datos de cada fila cambiarlo por una "s"
for i in range(filas):
    for j in range(len(x[i])):
        if j%5==0:
            x[i][j]="s"
print(x)
#Imprimir "aquí hay un multiplo de 7" cda que haya un multiplo de 7 en la matriz
filas=15
columnas=15
x=[]
for i in range(filas):
    x.append([])
    for j in range(columnas):
        x[i].append(random.randint(1,50))
#Se redefine la matriz x ya que la anterior tiene "s" en algunas entradas a las cuales no se les puede aplicar
#la función modulo
for i in range(filas):
    for j in range(len(x[i])):
        if x[i][j]%7==0:
            print("aquí hay un multiplo de 7")
#Multiplicar la matriz por 10
for i in range(filas):
    for j in range(len(x[i])):
        x[i][j]=x[i][j]*10
print(x)


[[41, 19, 19, 48, 30, 40, 1, 18, 16, 41, 24, 8, 48, 50, 38], [20, 8, 36, 50, 42, 6, 4, 9, 31, 32, 6, 3, 15, 34, 6], [37, 39, 49, 33, 13, 1, 41, 6, 1, 46, 14, 11, 15, 31, 47], [23, 1, 22, 3, 45, 21, 31, 2, 29, 34, 17, 47, 20, 39, 22], [15, 24, 19, 5, 17, 42, 34, 18, 2, 34, 13, 28, 40, 11, 16], [9, 12, 29, 35, 28, 45, 13, 20, 42, 10, 24, 37, 5, 40, 45], [24, 18, 25, 17, 40, 10, 24, 34, 50, 41, 3, 11, 3, 37, 25], [15, 24, 29, 42, 40, 7, 46, 35, 34, 3, 42, 27, 30, 10, 24], [46, 36, 36, 3, 34, 43, 48, 48, 42, 12, 32, 5, 36, 10, 1], [29, 23, 49, 8, 26, 11, 8, 43, 27, 1, 21, 21, 5, 7, 7], [46, 22, 7, 11, 3, 5, 33, 25, 23, 32, 37, 8, 27, 49, 49], [42, 1, 10, 40, 23, 6, 41, 48, 42, 44, 41, 24, 15, 34, 32], [21, 33, 5, 14, 19, 17, 48, 41, 9, 20, 14, 10, 28, 22, 48], [48, 31, 20, 50, 13, 36, 12, 12, 6, 49, 19, 29, 36, 42, 27], [20, 34, 21, 42, 9, 11, 41, 5, 44, 6, 4, 28, 14, 41, 1]]
[[41, 19, 19, 48, 30, 40, 1, 18, 16, 41, 24, 8, 48, 50, 0], [20, 8, 36, 50, 42, 6, 4, 9, 31, 32, 6, 3, 15, 0, 6], [

In [79]:
#Ejercicio 2(con numpy)
#Matriz de valores aleatorios de 3x3
A=np.random.rand(3,3)
B=np.random.rand(3,3)
C=A.dot(B)
print(C)
D=np.matmul(B,A)
print(D)
det_a=np.linalg.det(A)
det_b=np.linalg.det(B)
print("El determinante de la matriz A es: ",det_a,"El determinante de la matriz b es: ", det_b)
#Resolver el sistema de ecaciones dado
S1=np.matrix([[1,2,0],[2,3,-2],[-1,0,6]])
S2=np.matrix([[-3],[-10],[9]])
sol=np.linalg.solve(S1,S2)
print("La solución del sistema es: ",sol)

[[0.85242473 0.43836182 0.76899275]
 [1.40512987 0.57820925 1.28989561]
 [0.82915614 1.11829593 1.11017533]]
[[1.58365823 0.92234163 0.77013681]
 [0.81470138 0.34967644 0.58223864]
 [1.31999021 0.98779886 0.60747464]]
El determinante de la matriz A es:  0.2382887133013032 El determinante de la matriz b es:  -0.2422427749930645
La solución del sistema es:  [[-15.]
 [  6.]
 [ -1.]]


In [98]:
#Ejercicio de clase #fila por columna
#Realiza el codigo para multiplicar cualquier par de matrices cuadradas usando ciclos for
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([[1,5,6],[2,4,7],[1,4,3]])
print(x)
print(y)
mul=[[],[],[]]
mult=0
for i in range(len(x)):
    for j in range(len(x[i])):
        mult+=x[i][j]*y[j][i] 
    mul[i].append(mult)
    mult=0
mul

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 5 6]
 [2 4 7]
 [1 4 3]]


[[8], [64], [125]]